import { ArrowLeft } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { strategyApi } from '@/api/strategy'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { showToast } from '@/utils/toast'

interface BacktestItem {
  id: number
  symbol: string
  timeframe: string
  status: string
  start_date: string
  end_date: string
  capital: number
  win_rate: number
  returns: number
  created_at: string
  trades: unknown[]
}

/**
 * Historical backtest run log across every strategy in the registry.
 * Extracted from the old StrategyIndex "Backtest Logs" tab.
 */
export default function BacktestLogs() {
  const [globalBacktests, setGlobalBacktests] = useState<BacktestItem[]>([])
  const [loading, setLoading] = useState(false)

  const fetchGlobalBacktests = async () => {
    try {
      setLoading(true)
      const allBacktests: BacktestItem[] = []
      const userStrats = await strategyApi.getStrategies()

      for (const strat of userStrats) {
        const data = (await strategyApi.getBacktests(strat.id)) as {
          status: string
          backtests?: BacktestItem[]
        }
        if (data.status === 'success' && data.backtests) {
          allBacktests.push(...data.backtests)
        }
      }
      // Sort newest first
      allBacktests.sort((a, b) => b.id - a.id)
      setGlobalBacktests(allBacktests)
    } catch {
      showToast.error('Failed to load backtests history', 'strategy')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchGlobalBacktests()
    // biome-ignore lint/correctness/useExhaustiveDependencies: fetchGlobalBacktests is stable across renders
  }, [])

  return (
    <div className="container mx-auto py-6 space-y-6 max-w-7xl px-4 sm:px-6">
      <Button variant="ghost" size="sm" className="w-fit" asChild>
        <Link to="/strategy">
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Strategies
        </Link>
      </Button>

      <div>
        <h1 className="text-2xl font-bold tracking-tight">Backtest Logs</h1>
        <p className="text-muted-foreground">
          Historical run performance across every strategy in the registry.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Historical Run Performance History</CardTitle>
          <CardDescription>
            View performance and metrics generated by backtests across all registry strategies.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="space-y-2 animate-pulse">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-10 w-full" />
              ))}
            </div>
          ) : globalBacktests.length === 0 ? (
            <div className="text-center py-10 text-muted-foreground text-sm">
              No backtests run yet. Choose "Backtest" on any strategy card to generate metrics.
            </div>
          ) : (
            <div className="overflow-x-auto border border-border rounded-lg">
              <table className="w-full text-sm text-left">
                <thead className="bg-muted text-muted-foreground text-xs uppercase font-bold border-b">
                  <tr>
                    <th className="p-3">Job ID</th>
                    <th className="p-3">Asset Symbol</th>
                    <th className="p-3">Timeframe</th>
                    <th className="p-3">Period Range</th>
                    <th className="p-3 text-right">Capital</th>
                    <th className="p-3 text-right">Win Rate</th>
                    <th className="p-3 text-right">Returns</th>
                    <th className="p-3 text-center">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y">
                  {globalBacktests.map((b) => (
                    <tr key={b.id} className="hover:bg-muted/30">
                      <td className="p-3 font-semibold">#{b.id}</td>
                      <td className="p-3 font-semibold text-primary">{b.symbol}</td>
                      <td className="p-3">
                        <Badge variant="outline">{b.timeframe}</Badge>
                      </td>
                      <td className="p-3 text-xs text-muted-foreground">
                        {b.start_date} to {b.end_date}
                      </td>
                      <td className="p-3 text-right font-medium">
                        ₹{b.capital.toLocaleString()}
                      </td>
                      <td className="p-3 text-right font-bold text-profit">{b.win_rate}%</td>
                      <td className="p-3 text-right font-black text-info">
                        {b.returns > 0 ? '+' : ''}₹{b.returns.toLocaleString()}
                      </td>
                      <td className="p-3 text-center">
                        <Badge className="bg-profit/10 text-profit border-none font-bold text-[10px]">
                          {b.status}
                        </Badge>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
